---
- name: Perform recon on {{ target }}

 # Specify the hosts you want to target
  hosts: # Domain name
  gather_facts: True
  become: yes
  become_user: "{{ user_name }}"
  no_log: False

  vars:
    user_name: hunter
    target: 
    
  roles:
   - role: directory
     tags:
     - directory 

   - role: ip
     tags:
     - ip 

   - role: metabigor
     tags:
     - metabigor

   - role: amass
     tags:
     - amass

   - role: findomain
     tags:
     - findomain
     
   - role: dnsgen
     tags:
     - dnsgen  

   - role: Hakrawler
     tags:
     - Hakrawler

   - role: SubDomainizer
     tags:
     - SubDomainizer

   - role: assetfinder
     tags:
     - assetfinder 

   - role: FavFreak
     tags:
     - FavFreak

   - dnsWordlist
   - massdns
   - masscan
   - httprobe
   - nmap 
    #- vulners
   - scp 




 

   

   
      

    
 
   

    